title: WoWruRU Project
description: Русификация World of Warcraft 1.12.1
vk_group: WoWruRU
github_user: WoWruRU-ClassicAddons
google_analytics: UA-99828679-1

theme: jekyll-theme-slate

collections:
  addons:
    output: true
  changelog:
    output: true
